### ISSUE TITLE
Compatibility with esbuild-serve

### ISSUE THREAD

**Issue by chiroptical** [phenax/esbuild-plugin-elm#14]
Hello, I am pretty new to esbuild, elm, and this plugin. Is there a way to get this plugin to work with esbuild-serve?

I used this esbuild file for a very basic javascript example,

```js
#!/usr/bin/env node

import esbuildServe from "esbuild-serve";

esbuildServe(
  {
    logLevel: "info",
    // entryPoints: ["src/textAnimations.js"],
    entryPoints: ["src/layout.js"],
    bundle: true,
    outfile: "public/index.js",
  },
  { root: "public" }
);
```

I tried to port this over to a version using Elm using your example,

```js
#!/usr/bin/env node

import ElmPlugin from "esbuild-plugin-elm";
import esbuildServe from "esbuild-serve";

esbuildServe(
  {
    entryPoints: ["src/index.js"],
    bundle: true,
    outfile: "public/index.js",
    plugins: [
      ElmPlugin({
        debug: true,
        clearOnWatch: false,
      }),
    ],
  },
  { root: "public" }
)
```

I get,

```
node esbuild.config.js
 > node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:215:12: error: [elm] Invalid option from onResolve() callback in plugin "elm": "watchFiles"
    215 │       throw new Error(`Invalid option ${where}: "${key}"`);
        ╵             ^
    at checkForInvalidFlags (/home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:215:13)
    at callback (/home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:743:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleRequest (/home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:595:30)

   node_modules/esbuild-plugin-elm/index.js:34:10: note: This error came from the "onResolve" callback registered here
     34 │     build.onResolve({ filter: fileFilter }, async (args) => {
        ╵           ~~~~~~~~~
    at setup (/home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-plugin-elm/index.js:34:11)
    at handlePlugins (/home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:686:7)
    at Object.buildOrServe (/home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:903:44)
    at /home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:1444:17
    at new Promise (<anonymous>)
    at Object.build (/home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:1443:14)
    at Object.build (/home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/node_modules/esbuild/lib/main.js:1334:51)
    at esbuildServe (file:///home/chiroptical/programming/stream/cataract/elm-frontend/node_modules/esbuild-serve/src/index.js:8:4)
    at file:///home/chiroptical/programming/stream/cataract/elm-frontend/esbuild.config.js:6:1

   src/index.js:1:20: note: The plugin "elm" was triggered by this import
      1 │ import { Elm } from './Main.elm';
        ╵                     ~~~~~~~~~~~~

make: *** [Makefile:2: build] Error 1
```

My code is here: https://github.com/chiroptical/cataract/tree/elm (note the branch is `elm` **not** `main`). Any thoughts?

**Comment by phenax** [comment]
Seems like this is a problem with mismatching esbuild versions. You can open an issue with esbuild-serve to use a more open `>=0.9.0` esbuild version instead to be compatible with all plugins.

There is a workaround using yarn resolutions you can try out. Add the resolutions property in your package.json -
```
{
  // ...
  "resolutions": {
    "esbuild-serve/esbuild": ">=0.9.0"
  },
  // ...
}
```
